### ISSUE TITLE
noscript is still in HTML

### ISSUE THREAD

**Issue by marvinrabe** [itmayziii/gatsby-plugin-no-javascript#7]
Currently every file still contains the noscript and the "gatsby-focus-wrapper". They do not serve any purpose anymore. The noscript message is even wrong.

```
<noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript><div id="___gatsby"><div style="outline:none" tabindex="-1" role="group" id="gatsby-focus-wrapper"></div>
```

It would be best to remove those things.

**Comment by itmayziii** [comment]
@marvinrabe 

Agreed, will release a fix for this soon. It might be available as an option to be passed in the gatsby-config for those that still have other JS on the page and they want this <noscript>

**Comment by itmayziii** [comment]
According to  gatsbyjs/gatsby#13514 this bug does not seem possible to fix with the Gatsby APIs. If they ever expose an API capable of this then we can re-open the issue.

If you still want to remove the <noscript/> tag please look at the solutions provided in the Gatsby issue linked above.
